remote_theme: "mmistakes/minimal-mistakes"

include:
  - _pages

defaults:
  # _docs
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "sidebar"
